@baseUrl = http://localhost:3000

### Read all USER
GET {{baseUrl}}/auths/get

### Try to login an unknown user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"Martin",
    "password":"1"
}

### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"Luc",
    "password":"password"
}

### ADD WIN
POST {{baseUrl}}/score/winGame
Content-Type: application/json

{
    "username":"ia"
}

### ADD Lose
POST {{baseUrl}}/score/loseGame
Content-Type: application/json

{
    "username":"Julien"
}

### Number game
POST {{baseUrl}}/score/numberGame
Content-Type: application/json

{
    "username":"Martin"
}

### SORT
GET {{baseUrl}}/score/listOrder

